name: PhoenixNode Auto-Update

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if needed)
        run: |
          pip install -r requirements.txt || true

      - name: 🔁 Generate AI data & dashboard feed
        run: |
          python update_dashboard.py
          python build_dashboard_data.py

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json PhoenixNode_DashboardFeed.json
          git commit -m "📊 Auto-update dashboard feed"
          git push
      - name: Log signals to history
        run: |
         python signalHistory.py
