name: PhoenixNode Auto-Update

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Run Dashboard Update
        run: python update_dashboard.py

      - name: Commit and Push Changes
        run: |
          git config user.name "PhoenixNode AutoBot"
          git config user.email "actions@github.com"
          git add PhoenixNode_DashboardFeed.json
          git commit -m "🔄 Auto update dashboard feed"
          git push
