name: PhoenixNode Auto-Update

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate new status feed
        run: |
          echo "{
            \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
            \"deribit\": { \"momentum\": \"neutral\" },
            \"bridges\": { \"status\": \"stable\" },
            \"wallets\": { \"activity\": \"normal\" },
            \"deltaSignal\": 0.02
          }" > status.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add status.json
          git commit -m "⏱️ Update status feed"
          git push
